#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

echo "Checking commit message format..."
commit_regex='^(build|ci|docs|feat|fix|perf|refactor|revert|style|test|chore)(\([a-z0-9\-]+\))?: .{1,50}'
if ! echo "$commit_msg" | grep -qE "$commit_regex"; then
  echo "Error: Commit message does not match the required format."
  echo "Please use the following format: "
  echo "  <type>(<scope>): <subject>"
  echo "Example: feat(auth): add login feature"
  exit 1
fi

