#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running post-push tasks..."

# Send notification
echo "Sending push notification..."
curl -X POST -H 'Content-type: application/json' \
--data '{"text":"New code pushed!"}' \
"${WEBHOOK_URL}"

# Deploy to production
echo "Deploying to production..."
