#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running post-commit tasks..."

# Ensure the WEBHOOK_URL environment variable is set from GitHub environment
if [ -z "$Webhook_URL" ]; then
  echo "Error: WEBHOOK_URL is not set. Please configure the environment variable in your GitHub settings."
  exit 1
fi

# Send notification using the WEBHOOK_URL from the GitHub environment
echo "Sending commit notification..."
curl -X POST -H 'Content-type: application/json' \
--data "{\"text\":\"New commit made by $(logname)!\"}" \ "$Webhook_URL"

echo  "values is $Webhook_URL"

# Generate documentation (if uncommented)
# echo "Generating documentation..."
# ng run generate-docs

echo "Post-commit tasks completed."
