#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running post-commit tasks..."

# Send notification
echo "Sending commit notification..."
curl -X POST -H 'Content-type: application/json' \
--data "{\"text\":\"New commit made by $(logname)!\"}" \
"${Webhook_URL}"
# Generate documentation
echo "Generating documentation..."
#ng run generate-docs

echo "Post-commit tasks completed."
