#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running post-commit tasks..."

# Send notification
echo "Sending commit notification..."
curl -X POST -H 'Content-type: application/json' \
--data "{\"text\":\"New commit made by $(logname)!\"}" \
https://hooks.slack.com/services/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

# Generate documentation
echo "Generating documentation..."
#ng run generate-docs

echo "Post-commit tasks completed."
