#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "${GREEN}Running pre-commit tasks...${NC}"
# Run ESLint
echo "${GREEN}Running ESLint...${NC}"
ng lint

echo "${GREEN}Running ESLint formating...${NC}"
npm run lint
