#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "$(tput setaf 2)Running pre-push checks...$(tput sgr0)"

#Run tests
#echo "$(tput setaf 2)Running tests...$(tput sgr0)"
#npm test
#test_status=$?

# Run linting
echo "$(tput setaf 2)Running lint checks...$(tput sgr0)"
npm run lint
lint_status=$?

# Run build
echo "$(tput setaf 2)Running build...$(tput sgr0)"
npm run build
build_status=$?

# Run formatting checks
#echo "$(tput setaf 2)Checking code formatting...$(tput sgr0)"
#npm run format:check
#format_status=1?

# Check if any of the checks failed
if  [ "$lint_status" != 0 ]  || [ "$build_status" != 0 ]; then
#  || [ "$format_status" != 0 ]
#[ "$test_status" != 0 ] ||
  echo "$(tput setaf 1)Pre-push checks failed. Push aborted.$(tput sgr0)"
  exit 1
fi

echo "$(tput setaf 2)Pre-push checks passed. Proceeding with push.$(tput sgr0)"
